name: Check WSL Status
'on':
  - push
jobs:
  check-wsl-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Check WSL Status
        run: |
          df -kh
      - name: user
        run : |
          whoami
